# Generated by Django 3.0.4 on 2020-03-18 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200317_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smlrurl',
            name='smrl_url',
        ),
    ]
