# Generated by Django 3.0.2 on 2020-03-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmlrUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smlr_url_id', models.CharField(blank=True, max_length=500, null=True)),
                ('owner', models.CharField(blank=True, max_length=20, null=True)),
                ('destination_url', models.CharField(max_length=500, null=True)),
                ('visits', models.BigIntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('date_visited', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
